TheatreCMS4/TheatreCMS3/Areas/Blog/Controllers/BlogPhotoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TheatreCMS3.Areas.Blog.Models;
using TheatreCMS3.Models;
using System.IO;


namespace TheatreCMS3.Areas.Blog.Controllers
{
    public class BlogPhotoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Blog/BlogPhotoes
        public ActionResult Index()
        {
            return View(db.BlogPhotos.ToList());
        }

        // GET: Blog/BlogPhotoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPhoto blogPhoto = db.BlogPhotos.Find(id);
            if (blogPhoto == null)
            {
                return HttpNotFound();
            }
            return View(blogPhoto);
        }

        // GET: Blog/BlogPhotoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blog/BlogPhotoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BlogPhotoId,Title,Photo")] BlogPhoto blogPhoto, HttpPostedFileBase postedFile)
        {
            if (ModelState.IsValid)
            {               
                var photoByte = BlogPhotoByte(postedFile);
                blogPhoto.Photo = photoByte;
                db.BlogPhotos.Add(blogPhoto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPhoto);
        }

        // GET: Blog/BlogPhotoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPhoto blogPhoto = db.BlogPhotos.Find(id);
            if (blogPhoto == null)
            {
                return HttpNotFound();
            }
            return View(blogPhoto);
        }

        // POST: Blog/BlogPhotoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BlogPhotoId,Title,Photo")] BlogPhoto blogPhoto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blogPhoto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogPhoto);
        }

        // GET: Blog/BlogPhotoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPhoto blogPhoto = db.BlogPhotos.Find(id);
            if (blogPhoto == null)
            {
                return HttpNotFound();
            }
            return View(blogPhoto);
        }

        // POST: Blog/BlogPhotoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPhoto blogPhoto = db.BlogPhotos.Find(id);
            db.BlogPhotos.Remove(blogPhoto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public byte[] BlogPhotoByte(HttpPostedFileBase postedFile)
        {
            byte[] bytes;
            using (BinaryReader br = new BinaryReader(postedFile.InputStream))
            {
                bytes = br.ReadBytes(postedFile.ContentLength);
            }
            return bytes;
        }
    }
}

TheatreCMS4/TheatreCMS3/Areas/Blog/Views/BlogPhotoes/Create.cshtml
@model TheatreCMS3.Areas.Blog.Models.BlogPhoto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><strong>Create Blog Photo</strong></h2>


@using (Html.BeginForm("Create", "BlogPhotoes", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BlogPhoto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control input-field", @placeholder = "Enter title for the photo here." }})  
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
                <input class="fileSearch" type="file" id="postedFile" name="postedFile">
            </div>
        </div>

        <div class="form-group buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn blogphoto-create--btn" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn blogphoto-back-to-list--btn" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TheatreCMS4/TheatreCMS3/Areas/Blog/Views/BlogPhotoes/Delete.cshtml
@model TheatreCMS3.Areas.Blog.Models.BlogPhoto
    

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="blogphoto-delete--header">Delete this Blog Photo?</h2>

<div>   

    <div class="blogphoto-parentheader--header">
        <div class="blogphoto-titledisplay--header">@Html.DisplayNameFor(model => model.Title)</div>
        <div class="blogphoto-title--header">
            @Html.DisplayFor(model => model.Title)
        </div>

        @{var byteImage = Convert.ToBase64String(Model.Photo);}

        <div>
            <img src="data:image/jpg;base64, @byteImage" class="card-img-top blogphoto-cardImage--image" alt="Blog Photo failed to load" />
        </div>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div>
            <div>
                @Html.ActionLink("Edit", "Edit", new { id = Model.BlogPhotoId }, new { @class = "btn btn-secondary fa fa-camera blogphoto-edit-delete--btn" })
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary fas fa-arrow-alt-circle-left blogphoto-back-to-list-delete--btn" })
                <button onclick="location.href = '@Url.Action("Delete")'" class="btn blogphoto-delete-delete--btn">
                    <i class="fa fa-undo" aria-hidden="true">Delete</i>
                </button>
            </div>    
        </div>
    }

</div>

TheatreCMS4/TheatreCMS3/Areas/Blog/Views/BlogPhotoes/Details.cshtml
@model TheatreCMS3.Areas.Blog.Models.BlogPhoto

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="blogphoto-details--header">Blog Photo Details</h2>

<div>

    <div class="blogphoto-parentheader--header">
        <div class="blogphoto-titledisplay--header">@Html.DisplayNameFor(model => model.Title)</div>
        <div class="blogphoto-title--header">
            @Html.DisplayFor(model => model.Title)
        </div>

        @{var byteImage = Convert.ToBase64String(Model.Photo);}

        <div>
            <img src="data:image/jpg;base64, @byteImage" class="card-img-top blogphoto-cardImage--image" alt="Blog Photo failed to load" />
        </div>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div>
            <div>
                @Html.ActionLink("Edit", "Edit", new { id = Model.BlogPhotoId }, new { @class = "btn btn-secondary fa fa-camera blogphoto-edit-delete--btn" })
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary fas fa-arrow-alt-circle-left blogphoto-back-to-list-delete--btn" })
            </div>
        </div>
    }

</div>

TheatreCMS4/TheatreCMS3/Areas/Blog/Views/BlogPhotoes/Edit.cshtml
@model TheatreCMS3.Areas.Blog.Models.BlogPhoto

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><strong>Edit Blog Photo</strong></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BlogPhoto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BlogPhotoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control input-field", @placeholder = "Enter title for the photo here." } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control input-field" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn blogphoto-edit--btn" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn blogphoto-back-to-list--btn" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TheatreCMS4/TheatreCMS3/Areas/Blog/Views/BlogPhotoes/Index.cshtml
@model IEnumerable<TheatreCMS3.Areas.Blog.Models.BlogPhoto>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="card-columns blogphoto-myCardColumns--column">
    @foreach (var item in Model)
    {
        var byteImage = Convert.ToBase64String(item.Photo);

        <div class="card blogphoto-card--card">
            <a class="blogphoto-cardDetails--action" href="@Url.Action("Details", "BlogPhotoes", new { id = item.BlogPhotoId })"><img src="data:image/jpg;base64, @byteImage" class="card-img-top blogphoto-cardImage--image" alt="Blog Photo failed to load"></a>
            <p class="blogphoto-cardText--text">
                @Html.DisplayFor(modelItem => item.Title)
            </p>
            <p class="blogphoto-cardButtons--btn">
                @Html.ActionLink("Edit", "Edit", new { id = item.BlogPhotoId }, new { @class = "btn blogphoto-edit-index--btn" })
                @Html.ActionLink("Delete", "Delete", new { id = item.BlogPhotoId }, new { @class = "btn blogphoto-delete--btn" })
            </p>
        </div>
     }
</div>